"""
Quick example showing how to plot a sunpy map
 - A map is generated by reading in a fits file
 - the plot example is here:
   (https://docs.sunpy.org/en/stable/generated/gallery/plotting/aia_example.html)
 - For every one of our custom data types (maps/images) we'll write a quick method
   to produce a SunPy map that has the right metadata for plotting.
"""
import os

from chmap.settings.app import App

import sunpy.map
import matplotlib.pyplot as plt

# Use the reference images for this example
fits_infile_aia = os.path.join(App.APP_HOME, 'reference_data', 'aia_lev1_euv_12s_20140413T190507_193.fits')

# Load images image using the built-in methods of SunPy
# This creates a sunpy "map" structure which is a nice way to handle metadata
map_aia = sunpy.map.Map(fits_infile_aia)  # AIA is the EUV telescope on SDO

# now save a plot using the sunpy plot example
map_aia.plot()
map_aia.draw_limb()
plt.colorbar()
plt.show()
